default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *default
  database: stonk_development

test: &test
  <<: *default
  database: stonk_test

production:
